import types
from _typeshed import Incomplete
from build123d.build_common import Builder as Builder, WorkplaneList as WorkplaneList, logger as logger
from build123d.build_enums import Mode as Mode
from build123d.geometry import Location as Location, Plane as Plane
from build123d.topology import Curve as Curve, Edge as Edge, Face as Face

class BuildLine(Builder[Curve]):
    def __init__(self, workplane: Face | Plane | Location = ..., mode: Mode = ...) -> None: ...
    @property
    def line(self) -> Curve | None: ...
    @line.setter
    def line(self, value: Curve) -> None: ...
    exit_workplanes: Incomplete
    def __exit__(self, exception_type: type[BaseException] | None, exception_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def faces(self, *args) -> None: ...
    def face(self, *args) -> None: ...
    def solids(self, *args) -> None: ...
    def solid(self, *args) -> None: ...
