from _typeshed import Incomplete
from build123d.build_common import Builder as Builder, WorkplaneList as WorkplaneList
from build123d.build_enums import Mode as Mode
from build123d.geometry import Location as Location, Plane as Plane
from build123d.topology import Compound as Compound, Edge as Edge, Face as Face, ShapeList as ShapeList, Sketch as Sketch, Wire as Wire

class BuildSketch(Builder[Sketch]):
    mode: Incomplete
    pending_edges: ShapeList[Edge]
    def __init__(self, *workplanes: Face | Plane | Location, mode: Mode = ...) -> None: ...
    @property
    def sketch_local(self) -> Sketch | None: ...
    @sketch_local.setter
    def sketch_local(self, value: Sketch) -> None: ...
    @property
    def sketch(self): ...
    def solids(self, *args) -> None: ...
    def solid(self, *args) -> None: ...
    def consolidate_edges(self) -> Wire | list[Wire]: ...
