from OCP.GccEnt import GccEnt_enclosed, GccEnt_enclosing, GccEnt_noqualifier as GccEnt_noqualifier, GccEnt_outside, GccEnt_unqualified
from enum import Enum, IntEnum
from typing import TypeAlias

class Align(Enum):
    MIN = ...
    CENTER = ...
    MAX = ...
    NONE = None
Align2DType: TypeAlias = Align | None | tuple[Align | None, Align | None]
Align3DType: TypeAlias = Align | None | tuple[Align | None, Align | None, Align | None]

class ApproxOption(Enum):
    ARC = ...
    NONE = ...
    SPLINE = ...

class AngularDirection(Enum):
    CLOCKWISE = ...
    COUNTER_CLOCKWISE = ...

class CenterOf(Enum):
    GEOMETRY = ...
    MASS = ...
    BOUNDING_BOX = ...

class ContinuityLevel(IntEnum):
    C0 = 0
    C1 = 1
    C2 = 2

class Extrinsic(Enum):
    XYZ = ...
    XZY = ...
    YZX = ...
    YXZ = ...
    ZXY = ...
    ZYX = ...
    XYX = ...
    XZX = ...
    YZY = ...
    YXY = ...
    ZXZ = ...
    ZYZ = ...

class FrameMethod(Enum):
    FRENET = ...
    CORRECTED = ...

class GeomType(Enum):
    PLANE = ...
    CYLINDER = ...
    CONE = ...
    SPHERE = ...
    TORUS = ...
    BEZIER = ...
    BSPLINE = ...
    REVOLUTION = ...
    EXTRUSION = ...
    OFFSET = ...
    LINE = ...
    CIRCLE = ...
    ELLIPSE = ...
    HYPERBOLA = ...
    PARABOLA = ...
    OTHER = ...

class HeadType(Enum):
    STRAIGHT = ...
    CURVED = ...
    FILLETED = ...

class Intrinsic(Enum):
    XYZ = ...
    XZY = ...
    YZX = ...
    YXZ = ...
    ZXY = ...
    ZYX = ...
    XYX = ...
    XZX = ...
    YZY = ...
    YXY = ...
    ZXZ = ...
    ZYZ = ...

class Keep(Enum):
    ALL = ...
    BOTTOM = ...
    BOTH = ...
    INSIDE = ...
    OUTSIDE = ...
    TOP = ...

class Kind(Enum):
    ARC = ...
    INTERSECTION = ...
    TANGENT = ...

class Mode(Enum):
    ADD = ...
    SUBTRACT = ...
    INTERSECT = ...
    REPLACE = ...
    PRIVATE = ...

class FontStyle(Enum):
    REGULAR = ...
    BOLD = ...
    ITALIC = ...
    BOLDITALIC = ...

class Sagitta(Enum):
    SHORT = 0
    LONG = -1
    BOTH = 1

class LengthMode(Enum):
    DIAGONAL = ...
    HORIZONTAL = ...
    VERTICAL = ...

class MeshType(Enum):
    OTHER = ...
    MODEL = ...
    SUPPORT = ...
    SOLIDSUPPORT = ...

class NumberDisplay(Enum):
    DECIMAL = ...
    FRACTION = ...

class PageSize(Enum):
    A0 = ...
    A1 = ...
    A2 = ...
    A3 = ...
    A4 = ...
    A5 = ...
    A6 = ...
    A7 = ...
    A8 = ...
    A9 = ...
    A10 = ...
    LETTER = ...
    LEGAL = ...
    LEDGER = ...

class Tangency(Enum):
    UNQUALIFIED = GccEnt_unqualified
    ENCLOSING = GccEnt_enclosing
    ENCLOSED = GccEnt_enclosed
    OUTSIDE = GccEnt_outside

class PositionMode(Enum):
    LENGTH = ...
    PARAMETER = ...

class PrecisionMode(Enum):
    SESSION = 2
    GREATEST = 1
    AVERAGE = 0
    LEAST = -1

class Select(Enum):
    ALL = ...
    LAST = ...
    NEW = ...

class Side(Enum):
    LEFT = ...
    RIGHT = ...
    BOTH = ...

class SortBy(Enum):
    LENGTH = ...
    RADIUS = ...
    AREA = ...
    VOLUME = ...
    DISTANCE = ...

class TextAlign(Enum):
    BOTTOM = ...
    CENTER = ...
    LEFT = ...
    RIGHT = ...
    TOP = ...
    TOPFIRSTLINE = ...

class Transition(Enum):
    RIGHT = ...
    ROUND = ...
    TRANSFORMED = ...

class Unit(Enum):
    MC = ...
    MM = ...
    CM = ...
    M = ...
    IN = ...
    FT = ...

class Until(Enum):
    NEXT = ...
    LAST = ...
    PREVIOUS = ...
    FIRST = ...
