from _typeshed import Incomplete
from build123d.build_common import IN as IN, MM as MM
from build123d.build_enums import Align as Align, FontStyle as FontStyle, GeomType as GeomType, HeadType as HeadType, Mode as Mode, NumberDisplay as NumberDisplay, PageSize as PageSize, Side as Side, Unit as Unit
from build123d.build_line import BuildLine as BuildLine
from build123d.build_sketch import BuildSketch as BuildSketch
from build123d.geometry import Axis as Axis, Location as Location, Plane as Plane, Pos as Pos, Vector as Vector, VectorLike as VectorLike
from build123d.objects_curve import Line as Line, TangentArc as TangentArc
from build123d.objects_sketch import BaseSketchObject as BaseSketchObject, Polygon as Polygon, Text as Text
from build123d.operations_generic import fillet as fillet, mirror as mirror, sweep as sweep
from build123d.operations_sketch import make_face as make_face, trace as trace
from build123d.topology import Compound as Compound, Curve as Curve, Edge as Edge, ShapeList as ShapeList, Sketch as Sketch, Vertex as Vertex, Wire as Wire
from dataclasses import dataclass
from datetime import date
from typing import ClassVar, TypeAlias

class ArrowHead(BaseSketchObject):
    def __init__(self, size: float, head_type: HeadType = ..., rotation: float = 0, mode: Mode = ...) -> None: ...

class Arrow(BaseSketchObject):
    def __init__(self, arrow_size: float, shaft_path: Edge | Wire, shaft_width: float, head_at_start: bool = True, head_type: HeadType = ..., mode: Mode = ...) -> None: ...
PointLike: TypeAlias = Vector | Vertex | tuple[float, float, float]
PathDescriptor: TypeAlias = Wire | Edge | list[PointLike]

@dataclass
class Draft:
    unit_LUT: ClassVar[dict] = ...
    font_size: float = ...
    font: str = ...
    font_style: FontStyle = ...
    head_type: HeadType = ...
    arrow_length: float = ...
    line_width: float = ...
    pad_around_text: float = ...
    unit: Unit = ...
    number_display: NumberDisplay = ...
    display_units: bool = ...
    decimal_precision: int = ...
    fractional_precision: int = ...
    extension_gap: float = ...
    @property
    def is_metric(self) -> bool: ...
    def __post_init__(self) -> None: ...

class DimensionLine(BaseSketchObject):
    dimension: Incomplete
    def __init__(self, path: PathDescriptor, draft: Draft, sketch: Sketch | None = None, label: str | None = None, arrows: tuple[bool, bool] = (True, True), tolerance: float | tuple[float, float] | None = None, label_angle: bool = False, mode: Mode = ...) -> None: ...

class ExtensionLine(BaseSketchObject):
    dimension: Incomplete
    def __init__(self, border: PathDescriptor, offset: float, draft: Draft, sketch: Sketch | None = None, label: str | None = None, arrows: tuple[bool, bool] = (True, True), tolerance: float | tuple[float, float] | None = None, label_angle: bool = False, project_line: VectorLike | None = None, mode: Mode = ...) -> None: ...

class TechnicalDrawing(BaseSketchObject):
    page_sizes: Incomplete
    margin: Incomplete
    def __init__(self, designed_by: str = 'build123d', design_date: date | None = None, page_size: PageSize = ..., title: str = 'Title', sub_title: str = 'Sub Title', drawing_number: str = 'B3D-1', sheet_number: int | None = None, drawing_scale: float = 1.0, nominal_text_size: float = 10.0, line_width: float = 0.5, mode: Mode = ...) -> None: ...
