import xml.etree.ElementTree as ET
from OCP.Geom import Geom_BezierCurve as Geom_BezierCurve
from _typeshed import Incomplete
from build123d.build_common import UNITS_PER_METER as UNITS_PER_METER
from build123d.build_enums import GeomType as GeomType, Unit as Unit
from build123d.geometry import Color as Color, TOLERANCE as TOLERANCE, Vector as Vector, VectorLike as VectorLike
from build123d.topology import BoundBox as BoundBox, Compound as Compound, Edge as Edge, Shape as Shape, Wire as Wire
from collections.abc import Iterable
from enum import Enum
from ezdxf.colors import RGB
from os import PathLike
from typing import TypeAlias
from typing_extensions import Self

PathSegment: TypeAlias

class Drawing:
    visible_lines: Incomplete
    hidden_lines: Incomplete
    def __init__(self, shape: Shape, *, look_at: VectorLike | None = None, look_from: VectorLike = (1, -1, 1), look_up: VectorLike = (0, 0, 1), with_hidden: bool = True, focus: float | None = None) -> None: ...

class AutoNameEnum(Enum): ...

class LineType(AutoNameEnum):
    CONTINUOUS = ...
    BORDER = ...
    BORDER2 = ...
    BORDERX2 = ...
    CENTER = ...
    CENTER2 = ...
    CENTERX2 = ...
    DASHDOT = ...
    DASHDOT2 = ...
    DASHDOTX2 = ...
    DASHED = ...
    DASHED2 = ...
    DASHEDX2 = ...
    DIVIDE = ...
    DIVIDE2 = ...
    DIVIDEX2 = ...
    DOT = ...
    DOT2 = ...
    DOTX2 = ...
    HIDDEN = ...
    HIDDEN2 = ...
    HIDDENX2 = ...
    PHANTOM = ...
    PHANTOM2 = ...
    PHANTOMX2 = ...
    ISO_DASH = 'ACAD_ISO02W100'
    ISO_DASH_SPACE = 'ACAD_ISO03W100'
    ISO_LONG_DASH_DOT = 'ACAD_ISO04W100'
    ISO_LONG_DASH_DOUBLE_DOT = 'ACAD_ISO05W100'
    ISO_LONG_DASH_TRIPLE_DOT = 'ACAD_ISO06W100'
    ISO_DOT = 'ACAD_ISO07W100'
    ISO_LONG_DASH_SHORT_DASH = 'ACAD_ISO08W100'
    ISO_LONG_DASH_DOUBLE_SHORT_DASH = 'ACAD_ISO09W100'
    ISO_DASH_DOT = 'ACAD_ISO10W100'
    ISO_DOUBLE_DASH_DOT = 'ACAD_ISO11W100'
    ISO_DASH_DOUBLE_DOT = 'ACAD_ISO12W100'
    ISO_DOUBLE_DASH_DOUBLE_DOT = 'ACAD_ISO13W100'
    ISO_DASH_TRIPLE_DOT = 'ACAD_ISO14W100'
    ISO_DOUBLE_DASH_TRIPLE_DOT = 'ACAD_ISO15W100'

class ColorIndex(Enum):
    RED = 1
    YELLOW = 2
    GREEN = 3
    CYAN = 4
    BLUE = 5
    MAGENTA = 6
    BLACK = 7
    GRAY = 8
    LIGHT_GRAY = 9

class DotLength(Enum):
    TRUE_DOT = 0.0
    INKSCAPE_COMPAT = 0.01
    QCAD_IMPERIAL = 0.2

def ansi_pattern(*args): ...
def iso_pattern(*args): ...
def unit_conversion_scale(from_unit: Unit, to_unit: Unit) -> float: ...

class Export2D:
    PARAMETRIC_TOLERANCE: float
    DEFAULT_COLOR_INDEX: Incomplete
    DEFAULT_LINE_WEIGHT: float
    DEFAULT_LINE_TYPE: Incomplete
    LINETYPE_DEFS: Incomplete
    LTYPE_SCALE: Incomplete

class ExportDXF(Export2D):
    METRIC_UNITS: Incomplete
    def __init__(self, version: str = ..., unit: Unit = ..., color: ColorIndex | None = None, line_weight: float | None = None, line_type: LineType | None = None) -> None: ...
    def add_layer(self, name: str, *, color: ColorIndex | None = None, line_weight: float | None = None, line_type: LineType | None = None) -> Self: ...
    def add_shape(self, shape: Shape | Iterable[Shape], layer: str = '') -> Self: ...
    def write(self, file_name: PathLike | str | bytes): ...

class ExportSVG(Export2D):
    class _Layer:
        name: Incomplete
        fill_color: Incomplete
        line_color: Incomplete
        line_weight: Incomplete
        line_type: Incomplete
        elements: list[ET.Element]
        def __init__(self, name: str, fill_color: ColorIndex | RGB | Color | None, line_color: ColorIndex | RGB | Color | None, line_weight: float, line_type: LineType) -> None: ...
    unit: Incomplete
    scale: Incomplete
    margin: Incomplete
    fit_to_stroke: Incomplete
    precision: Incomplete
    dot_length: Incomplete
    def __init__(self, unit: Unit = ..., scale: float = 1, margin: float = 0, fit_to_stroke: bool = True, precision: int = 6, fill_color: ColorIndex | RGB | Color | None = None, line_color: ColorIndex | RGB | Color | None = ..., line_weight: float = ..., line_type: LineType = ..., dot_length: DotLength | float = ...) -> None: ...
    def add_layer(self, name: str, *, fill_color: ColorIndex | RGB | Color | None = None, line_color: ColorIndex | RGB | Color | None = ..., line_weight: float = ..., line_type: LineType = ...) -> Self: ...
    def add_shape(self, shape: Shape | Iterable[Shape], layer: str = '', reverse_wires: bool = False): ...
    def write(self, path: PathLike | str | bytes): ...
