import json
from .topology import Edge as Edge, Face as Face, Shape as Shape, Vertex as Vertex
from OCP.Bnd import Bnd_Box, Bnd_OBB
from OCP.Quantity import Quantity_ColorRGBA
from OCP.TopLoc import TopLoc_Location
from OCP.TopoDS import TopoDS_Face, TopoDS_Shape
from OCP.gp import gp_Ax1, gp_Ax2, gp_Dir, gp_GTrsf, gp_Pln, gp_Pnt, gp_Trsf, gp_Vec, gp_XYZ
from _typeshed import Incomplete
from build123d.build_enums import Align as Align, Align2DType as Align2DType, Align3DType as Align3DType, Extrinsic as Extrinsic, Intrinsic as Intrinsic
from collections.abc import Callable as Callable, Iterable, Sequence
from typing import Any, TypeAlias, overload

logger: Incomplete
TOLERANCE: float
TOL_DIGITS: Incomplete
TOL: float
DEG2RAD: Incomplete
RAD2DEG: Incomplete

class Vector:
    @overload
    def __init__(self, X: float, Y: float, Z: float) -> None: ...
    @overload
    def __init__(self, X: float, Y: float) -> None: ...
    @overload
    def __init__(self, v: Vector) -> None: ...
    @overload
    def __init__(self, v: Sequence[float]) -> None: ...
    @overload
    def __init__(self, v: gp_Vec | gp_Pnt | gp_Dir | gp_XYZ) -> None: ...
    @overload
    def __init__(self) -> None: ...
    vector_index: int
    def __iter__(self): ...
    def __next__(self): ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> None: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> None: ...
    @property
    def Z(self) -> float: ...
    @Z.setter
    def Z(self, value: float) -> None: ...
    @property
    def wrapped(self) -> gp_Vec: ...
    def to_tuple(self) -> tuple[float, float, float]: ...
    @property
    def length(self) -> float: ...
    def cross(self, vec: Vector) -> Vector: ...
    def dot(self, vec: Vector) -> float: ...
    def sub(self, vec: VectorLike) -> Vector: ...
    def __sub__(self, vec: VectorLike) -> Vector: ...
    def add(self, vec: VectorLike) -> Vector: ...
    def __add__(self, vec: VectorLike) -> Vector: ...
    def __radd__(self, vec: Vector) -> Vector: ...
    def multiply(self, scale: float) -> Vector: ...
    def __mul__(self, scale: float) -> Vector: ...
    def __truediv__(self, denom: float) -> Vector: ...
    def __rmul__(self, scale: float) -> Vector: ...
    def normalized(self) -> Vector: ...
    def reverse(self) -> Vector: ...
    def center(self) -> Vector: ...
    def get_angle(self, vec: Vector) -> float: ...
    def get_signed_angle(self, vec: Vector, normal: Vector | None = None) -> float: ...
    def project_to_line(self, line: Vector) -> Vector: ...
    def distance_to_plane(self, plane: Plane) -> float: ...
    def signed_distance_from_plane(self, plane: Plane) -> float: ...
    def project_to_plane(self, plane: Plane) -> Vector: ...
    def __neg__(self) -> Vector: ...
    def __abs__(self) -> float: ...
    def __and__(self, other: Axis | Location | Plane | VectorLike | Shape): ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __copy__(self) -> Vector: ...
    def __deepcopy__(self, _memo) -> Vector: ...
    def to_pnt(self) -> gp_Pnt: ...
    def to_dir(self) -> gp_Dir: ...
    def transform(self, affine_transform: Matrix, is_direction: bool = False) -> Vector: ...
    def rotate(self, axis: Axis, angle: float) -> Vector: ...
    @overload
    def intersect(self, vector: VectorLike) -> Vector | None: ...
    @overload
    def intersect(self, location: Location) -> Vector | None: ...
    @overload
    def intersect(self, axis: Axis) -> Vector | None: ...
    @overload
    def intersect(self, plane: Plane) -> Vector | None: ...
    @overload
    def intersect(self, shape: Shape) -> Shape | None: ...
VectorLike: TypeAlias = Vector | tuple[float, float] | tuple[float, float, float] | Sequence[float]

class AxisMeta(type):
    @property
    def X(cls) -> Axis: ...
    @property
    def Y(cls) -> Axis: ...
    @property
    def Z(cls) -> Axis: ...

class Axis(metaclass=AxisMeta):
    @overload
    def __init__(self, gp_ax1: gp_Ax1) -> None: ...
    @overload
    def __init__(self, location: Location) -> None: ...
    @overload
    def __init__(self, origin: VectorLike, direction: VectorLike) -> None: ...
    @overload
    def __init__(self, edge: Edge) -> None: ...
    @property
    def position(self) -> Vector: ...
    @position.setter
    def position(self, position: VectorLike): ...
    @property
    def direction(self) -> Vector: ...
    @direction.setter
    def direction(self, direction: VectorLike): ...
    @property
    def location(self) -> Location: ...
    def __copy__(self) -> Axis: ...
    def __deepcopy__(self, _memo) -> Axis: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def located(self, new_location: Location): ...
    def to_plane(self) -> Plane: ...
    def is_coaxial(self, other: Axis, angular_tolerance: float = 1e-05, linear_tolerance: float = 1e-05) -> bool: ...
    def is_normal(self, other: Axis, angular_tolerance: float = 1e-05) -> bool: ...
    def is_opposite(self, other: Axis, angular_tolerance: float = 1e-05) -> bool: ...
    def is_parallel(self, other: Axis, angular_tolerance: float = 1e-05) -> bool: ...
    def is_skew(self, other: Axis, tolerance: float = 1e-05) -> bool: ...
    def angle_between(self, other: Axis) -> float: ...
    def reverse(self) -> Axis: ...
    def __neg__(self) -> Axis: ...
    def __and__(self, other: Axis | Location | Plane | VectorLike | Shape) -> Vector | Location | Axis | None: ...
    @overload
    def intersect(self, vector: VectorLike) -> Vector | None: ...
    @overload
    def intersect(self, location: Location) -> Vector | Location | None: ...
    @overload
    def intersect(self, axis: Axis) -> Vector | Axis | None: ...
    @overload
    def intersect(self, plane: Plane) -> Vector | Axis | None: ...
    @overload
    def intersect(self, shape: Shape) -> Shape | None: ...

class BoundBox:
    wrapped: Incomplete
    min: Incomplete
    max: Incomplete
    size: Incomplete
    def __init__(self, bounding_box: Bnd_Box) -> None: ...
    @property
    def diagonal(self) -> float: ...
    def center(self) -> Vector: ...
    def add(self, obj: tuple[float, float, float] | Vector | BoundBox, tol: float | None = None) -> BoundBox: ...
    @staticmethod
    def find_outside_box_2d(bb1: BoundBox, bb2: BoundBox) -> BoundBox | None: ...
    @classmethod
    def from_topo_ds(cls, shape: TopoDS_Shape, tolerance: float | None = None, optimal: bool = True) -> BoundBox: ...
    def is_inside(self, second_box: BoundBox) -> bool: ...
    def to_align_offset(self, align: Align2DType | Align3DType) -> Vector: ...

class Color:
    @overload
    def __init__(self, color_like: ColorLike) -> None: ...
    @overload
    def __init__(self, name: str, alpha: float = 1.0) -> None: ...
    @overload
    def __init__(self, red: float, green: float, blue: float, alpha: float = 1.0) -> None: ...
    @overload
    def __init__(self, color_code: int, alpha: int = 255) -> None: ...
    iter_index: int
    def __iter__(self): ...
    def __next__(self): ...
    def to_tuple(self): ...
    def __copy__(self) -> Color: ...
    def __deepcopy__(self, _memo) -> Color: ...
ColorLike: TypeAlias = str | tuple[str, float | int] | tuple[float | int, float | int, float | int] | tuple[float | int, float | int, float | int, float | int] | int | tuple[int, int] | Color | Quantity_ColorRGBA

class GeomEncoder(json.JSONEncoder):
    def default(self, o): ...
    @staticmethod
    def geometry_hook(json_dict): ...

class Location:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, location: Location) -> None: ...
    @overload
    def __init__(self, translation: VectorLike, angle: float = 0) -> None: ...
    @overload
    def __init__(self, translation: VectorLike, rotation: RotationLike | None = None) -> None: ...
    @overload
    def __init__(self, translation: VectorLike, rotation: RotationLike, ordering: Extrinsic | Intrinsic) -> None: ...
    @overload
    def __init__(self, plane: Plane) -> None: ...
    @overload
    def __init__(self, plane: Plane, plane_offset: VectorLike) -> None: ...
    @overload
    def __init__(self, top_loc: TopLoc_Location) -> None: ...
    @overload
    def __init__(self, gp_trsf: gp_Trsf) -> None: ...
    @overload
    def __init__(self, translation: VectorLike, direction: VectorLike, angle: float) -> None: ...
    @property
    def position(self) -> Vector: ...
    wrapped: Incomplete
    @position.setter
    def position(self, value: VectorLike): ...
    @property
    def orientation(self) -> Vector: ...
    @orientation.setter
    def orientation(self, rotation: VectorLike): ...
    @property
    def x_axis(self) -> Axis: ...
    @property
    def y_axis(self) -> Axis: ...
    @property
    def z_axis(self) -> Axis: ...
    def inverse(self) -> Location: ...
    def __copy__(self) -> Location: ...
    def __deepcopy__(self, _memo) -> Location: ...
    @overload
    def __mul__(self, other: Shape) -> Shape: ...
    @overload
    def __mul__(self, other: Location) -> Location: ...
    @overload
    def __mul__(self, other: Iterable[Location]) -> list[Location]: ...
    def __pow__(self, exponent: int) -> Location: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    location_index: int
    def __iter__(self): ...
    def __next__(self) -> Vector: ...
    def __neg__(self) -> Location: ...
    def __and__(self, other: Axis | Location | Plane | VectorLike | Shape) -> Vector | Location | None: ...
    def center(self) -> Vector: ...
    def mirror(self, mirror_plane: Plane) -> Location: ...
    def to_axis(self) -> Axis: ...
    def to_tuple(self) -> tuple[tuple[float, float, float], tuple[float, float, float]]: ...
    @overload
    def intersect(self, vector: VectorLike) -> Vector | None: ...
    @overload
    def intersect(self, location: Location) -> Vector | Location | None: ...
    @overload
    def intersect(self, axis: Axis) -> Vector | Location | None: ...
    @overload
    def intersect(self, plane: Plane) -> Vector | Location | None: ...
    @overload
    def intersect(self, shape: Shape) -> Shape | None: ...

class LocationEncoder(json.JSONEncoder):
    def default(self, o: Location) -> dict: ...
    @staticmethod
    def location_hook(obj) -> dict: ...

class OrientedBoundBox:
    wrapped: Incomplete
    def __init__(self, shape: Bnd_OBB | Shape) -> None: ...
    @property
    def corners(self) -> list[Vector]: ...
    @property
    def diagonal(self) -> float: ...
    @property
    def location(self) -> Location: ...
    @property
    def plane(self) -> Plane: ...
    @property
    def size(self) -> Vector: ...
    @property
    def x_direction(self) -> Vector: ...
    @property
    def y_direction(self) -> Vector: ...
    @property
    def z_direction(self) -> Vector: ...
    def center(self) -> Vector: ...
    def is_completely_inside(self, other: OrientedBoundBox) -> bool: ...
    def is_outside(self, point: Vector) -> bool: ...

class Rotation(Location):
    @overload
    def __init__(self, rotation: RotationLike, ordering: None) -> None: ...
    @overload
    def __init__(self, X: float = 0, Y: float = 0, Z: float = 0, ordering: Extrinsic | Intrinsic = ...) -> None: ...
Rot = Rotation
RotationLike: TypeAlias = Rotation | tuple[float, float, float]

class Pos(Location):
    @overload
    def __init__(self, v: VectorLike) -> None: ...
    @overload
    def __init__(self, v: Iterable) -> None: ...
    @overload
    def __init__(self, X: float = 0, Y: float = 0, Z: float = 0) -> None: ...

class Matrix:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, trsf: gp_GTrsf | gp_Trsf) -> None: ...
    @overload
    def __init__(self, matrix: Sequence[Sequence[float]]) -> None: ...
    wrapped: Incomplete
    def rotate(self, axis: Axis, angle: float): ...
    def inverse(self) -> Matrix: ...
    @overload
    def multiply(self, other: Vector) -> Vector: ...
    @overload
    def multiply(self, other: Matrix) -> Matrix: ...
    def transposed_list(self) -> Sequence[float]: ...
    def __copy__(self) -> Matrix: ...
    def __deepcopy__(self, _memo) -> Matrix: ...
    def __getitem__(self, row_col: tuple[int, int]) -> float: ...

class PlaneMeta(type):
    @property
    def XY(cls) -> Plane: ...
    @property
    def YZ(cls) -> Plane: ...
    @property
    def ZX(cls) -> Plane: ...
    @property
    def XZ(cls) -> Plane: ...
    @property
    def YX(cls) -> Plane: ...
    @property
    def ZY(cls) -> Plane: ...
    @property
    def front(cls) -> Plane: ...
    @property
    def back(cls) -> Plane: ...
    @property
    def left(cls) -> Plane: ...
    @property
    def right(cls) -> Plane: ...
    @property
    def top(cls) -> Plane: ...
    @property
    def bottom(cls) -> Plane: ...
    @property
    def isometric(cls) -> Plane: ...

class Plane(metaclass=PlaneMeta):
    @staticmethod
    def get_topods_face_normal(face: TopoDS_Face) -> Vector: ...
    @overload
    def __init__(self, gp_pln: gp_Pln) -> None: ...
    @overload
    def __init__(self, origin: VectorLike, x_dir: VectorLike | None = None, z_dir: VectorLike = (0, 0, 1)) -> None: ...
    @overload
    def __init__(self, face: Face, x_dir: VectorLike | None = None) -> None: ...
    @overload
    def __init__(self, location: Location) -> None: ...
    @overload
    def __init__(self, axis: Axis, x_dir: VectorLike | None = None) -> None: ...
    def offset(self, amount: float) -> Plane: ...
    def __copy__(self) -> Plane: ...
    def __deepcopy__(self, _memo) -> Plane: ...
    def __eq__(self, other: object): ...
    def __hash__(self) -> int: ...
    def __neg__(self) -> Plane: ...
    def __mul__(self, other: Location | Shape) -> Plane | list[Plane] | Shape: ...
    def __and__(self, other: Axis | Location | Plane | VectorLike | Shape): ...
    def reverse(self) -> Plane: ...
    @property
    def origin(self) -> Vector: ...
    wrapped: Incomplete
    @origin.setter
    def origin(self, value) -> None: ...
    def shift_origin(self, locator: Axis | VectorLike | Vertex) -> Plane: ...
    def rotated(self, rotation: VectorLike = (0, 0, 0), ordering: Extrinsic | Intrinsic | None = None) -> Plane: ...
    def move(self, loc: Location) -> Plane: ...
    @property
    def location(self) -> Location: ...
    def to_gp_ax2(self) -> gp_Ax2: ...
    def to_local_coords(self, obj: VectorLike | Any | BoundBox): ...
    def from_local_coords(self, obj: tuple | Vector | Any | BoundBox): ...
    def location_between(self, other: Plane) -> Location: ...
    def contains(self, obj: VectorLike | Axis, tolerance: float = ...) -> bool: ...
    @overload
    def intersect(self, vector: VectorLike) -> Vector | None: ...
    @overload
    def intersect(self, location: Location) -> Vector | Location | None: ...
    @overload
    def intersect(self, axis: Axis) -> Vector | Axis | None: ...
    @overload
    def intersect(self, plane: Plane) -> Axis | Plane | None: ...
    @overload
    def intersect(self, shape: Shape) -> Shape | None: ...

CLASS_REGISTRY: Incomplete

def to_align_offset(min_point: VectorLike, max_point: VectorLike, align: Align2DType | Align3DType, center: VectorLike | None = None) -> Vector: ...
