from _typeshed import Incomplete
from build123d.build_common import validate_inputs as validate_inputs
from build123d.build_enums import Align as Align
from build123d.build_part import BuildPart as BuildPart
from build123d.geometry import Axis as Axis, Location as Location, Plane as Plane, Rotation as Rotation, RotationLike as RotationLike, Vector as Vector, VectorLike as VectorLike
from build123d.topology import Compound as Compound, Edge as Edge, Joint as Joint, Solid as Solid
from typing import overload

class RigidJoint(Joint):
    @property
    def location(self) -> Location: ...
    @property
    def symbol(self) -> Compound: ...
    relative_location: Incomplete
    def __init__(self, label: str, to_part: Solid | Compound | None = None, joint_location: Location | None = None) -> None: ...
    @overload
    def connect_to(self, other: BallJoint, *, angles: RotationLike | None = None, **kwargs): ...
    @overload
    def connect_to(self, other: CylindricalJoint, *, position: float | None = None, angle: float | None = None): ...
    @overload
    def connect_to(self, other: LinearJoint, *, position: float | None = None): ...
    @overload
    def connect_to(self, other: RevoluteJoint, *, angle: float | None = None): ...
    @overload
    def connect_to(self, other: RigidJoint): ...
    @overload
    def relative_to(self, other: BallJoint, *, angles: RotationLike | None = None): ...
    @overload
    def relative_to(self, other: CylindricalJoint, *, position: float | None = None, angle: float | None = None): ...
    @overload
    def relative_to(self, other: LinearJoint, *, position: float | None = None): ...
    @overload
    def relative_to(self, other: RevoluteJoint, *, angle: float | None = None): ...
    @overload
    def relative_to(self, other: RigidJoint): ...

class RevoluteJoint(Joint):
    @property
    def location(self) -> Location: ...
    @property
    def symbol(self) -> Compound: ...
    angular_range: Incomplete
    angle_reference: Incomplete
    relative_axis: Incomplete
    def __init__(self, label: str, to_part: Solid | Compound | None = None, axis: Axis = ..., angle_reference: VectorLike | None = None, angular_range: tuple[float, float] = (0, 360)) -> None: ...
    def connect_to(self, other: RigidJoint, *, angle: float | None = None): ...
    def relative_to(self, other: RigidJoint, *, angle: float | None = None): ...

class LinearJoint(Joint):
    @property
    def location(self) -> Location: ...
    @property
    def symbol(self) -> Compound: ...
    axis: Incomplete
    linear_range: Incomplete
    position: Incomplete
    relative_axis: Incomplete
    angle: Incomplete
    def __init__(self, label: str, to_part: Solid | Compound | None = None, axis: Axis = ..., linear_range: tuple[float, float] = ...) -> None: ...
    @overload
    def connect_to(self, other: RevoluteJoint, *, position: float | None = None, angle: float | None = None): ...
    @overload
    def connect_to(self, other: RigidJoint, *, position: float | None = None): ...
    @overload
    def relative_to(self, other: RigidJoint, *, position: float | None = None): ...
    @overload
    def relative_to(self, other: RevoluteJoint, *, position: float | None = None, angle: float | None = None): ...

class CylindricalJoint(Joint):
    @property
    def location(self) -> Location: ...
    @property
    def symbol(self) -> Compound: ...
    axis: Incomplete
    linear_position: Incomplete
    rotational_position: Incomplete
    angle_reference: Incomplete
    angular_range: Incomplete
    linear_range: Incomplete
    relative_axis: Incomplete
    position: float | None
    angle: float | None
    def __init__(self, label: str, to_part: Solid | Compound | None = None, axis: Axis = ..., angle_reference: VectorLike | None = None, linear_range: tuple[float, float] = ..., angular_range: tuple[float, float] = (0, 360)) -> None: ...
    def connect_to(self, other: RigidJoint, *, position: float | None = None, angle: float | None = None): ...
    def relative_to(self, other: RigidJoint, *, position: float | None = None, angle: float | None = None): ...

class BallJoint(Joint):
    @property
    def location(self) -> Location: ...
    @property
    def symbol(self) -> Compound: ...
    relative_location: Incomplete
    angular_range: Incomplete
    angle_reference: Incomplete
    def __init__(self, label: str, to_part: Solid | Compound | None = None, joint_location: Location | None = None, angular_range: tuple[tuple[float, float], tuple[float, float], tuple[float, float]] = ((0, 360), (0, 360), (0, 360)), angle_reference: Plane = ...) -> None: ...
    def connect_to(self, other: RigidJoint, *, angles: RotationLike | None = None): ...
    def relative_to(self, other: RigidJoint, *, angles: RotationLike | None = None): ...
