from _typeshed import Incomplete
from build123d.build_enums import MeshType as MeshType, Unit as Unit
from build123d.geometry import Color as Color, TOLERANCE as TOLERANCE
from build123d.topology import Compound as Compound, Shape as Shape, Shell as Shell, Solid as Solid, downcast as downcast
from collections.abc import Iterable
from lib3mf import Lib3MF
from os import PathLike
from uuid import UUID

class Mesher:
    unit: Incomplete
    wrapper: Incomplete
    model: Incomplete
    meshes: list[Lib3MF.MeshObject]
    def __init__(self, unit: Unit = ...) -> None: ...
    @property
    def model_unit(self) -> Unit: ...
    @property
    def triangle_counts(self) -> list[int]: ...
    @property
    def vertex_counts(self) -> list[int]: ...
    @property
    def mesh_count(self) -> int: ...
    @property
    def library_version(self) -> str: ...
    def add_meta_data(self, name_space: str, name: str, value: str, metadata_type: str, must_preserve: bool): ...
    def add_code_to_metadata(self) -> None: ...
    def get_meta_data(self) -> list[dict]: ...
    def get_meta_data_by_key(self, name_space: str, name: str) -> dict: ...
    def get_mesh_properties(self) -> list[dict]: ...
    def add_shape(self, shape: Shape | Iterable[Shape], linear_deflection: float = 0.001, angular_deflection: float = 0.1, mesh_type: MeshType = ..., part_number: str | None = None, uuid_value: UUID | None = None): ...
    def read(self, file_name: PathLike | str | bytes) -> list[Shape]: ...
    def write(self, file_name: PathLike | str | bytes): ...
