from build123d.build_common import flatten_sequence as flatten_sequence, validate_inputs as validate_inputs
from build123d.build_enums import Mode as Mode, SortBy as SortBy, Transition as Transition
from build123d.build_sketch import BuildSketch as BuildSketch
from build123d.geometry import Plane as Plane, TOLERANCE as TOLERANCE, Vector as Vector
from build123d.topology import Compound as Compound, Curve as Curve, Edge as Edge, Face as Face, ShapeList as ShapeList, Shell as Shell, Sketch as Sketch, Wire as Wire, topo_explore_common_vertex as topo_explore_common_vertex, topo_explore_connected_edges as topo_explore_connected_edges
from collections.abc import Iterable

def full_round(edge: Edge, invert: bool = False, voronoi_point_count: int = 100, mode: Mode = ...) -> tuple[Sketch, Vector, float]: ...
def make_face(edges: Edge | Iterable[Edge] | None = None, mode: Mode = ...) -> Sketch: ...
def make_hull(edges: Edge | Iterable[Edge] | None = None, mode: Mode = ...) -> Sketch: ...
def trace(lines: Curve | Edge | Wire | Iterable[Curve | Edge | Wire] | None = None, line_width: float = 1, mode: Mode = ...) -> Sketch: ...
