from build123d.build_common import WorkplaneList as WorkplaneList, flatten_sequence as flatten_sequence, logger as logger, validate_inputs as validate_inputs
from build123d.build_enums import GeomType as GeomType, Kind as Kind, Mode as Mode, Side as Side, Until as Until
from build123d.build_part import BuildPart as BuildPart
from build123d.geometry import Axis as Axis, Plane as Plane, Vector as Vector, VectorLike as VectorLike
from build123d.topology import Compound as Compound, Curve as Curve, DraftAngleError as DraftAngleError, Edge as Edge, Face as Face, Part as Part, ShapeList as ShapeList, Shell as Shell, Sketch as Sketch, Solid as Solid, Vertex as Vertex, Wire as Wire
from collections.abc import Iterable

def draft(faces: Face | Iterable[Face], neutral_plane: Plane, angle: float) -> Part: ...
def extrude(to_extrude: Face | Sketch | None = None, amount: float | None = None, dir: VectorLike | None = None, until: Until | None = None, target: Compound | Solid | None = None, both: bool = False, taper: float = 0.0, clean: bool = True, mode: Mode = ...) -> Part: ...
def loft(sections: Face | Sketch | Iterable[Vertex | Face | Sketch] | None = None, ruled: bool = False, clean: bool = True, mode: Mode = ...) -> Part: ...
def make_brake_formed(thickness: float, station_widths: float | Iterable[float], line: Edge | Wire | Curve | None = None, side: Side = ..., kind: Kind = ..., clean: bool = True, mode: Mode = ...) -> Part: ...
def project_workplane(origin: VectorLike | Vertex, x_dir: VectorLike | Vertex, projection_dir: VectorLike, distance: float) -> Plane: ...
def revolve(profiles: Face | Iterable[Face] | None = None, axis: Axis = ..., revolution_arc: float = 360.0, clean: bool = True, mode: Mode = ...) -> Part: ...
def section(obj: Part | None = None, section_by: Plane | Iterable[Plane] = ..., height: float = 0.0, clean: bool = True, mode: Mode = ...) -> Sketch: ...
def thicken(to_thicken: Face | Sketch | None = None, amount: float | None = None, normal_override: VectorLike | None = None, both: bool = False, clean: bool = True, mode: Mode = ...) -> Part: ...
