from OCP.TopLoc import TopLoc_Location
from OCP.TopoDS import TopoDS_Shape
from build123d.topology import downcast as downcast

def serialize_shape(shape: TopoDS_Shape) -> bytes | None: ...
def deserialize_shape(buffer: bytes) -> TopoDS_Shape: ...
def serialize_location(location: TopLoc_Location) -> bytes | None: ...
def deserialize_location(buffer: bytes) -> TopLoc_Location: ...
def reduce_shape(shape: TopoDS_Shape) -> tuple: ...
def reduce_location(location: TopLoc_Location) -> tuple: ...
def modify_copyreg() -> None: ...
