#!/usr/bin/env python3
"""Post-install venv setup: fast ezdxf imports on macOS and smoke-check CAD imports."""

from __future__ import annotations

import os
import platform
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
VENV_PYTHON = REPO_ROOT / ".venv" / "bin" / "python"

SITECUSTOMIZE = """\
# Generated by prepare_venv.py — keep ezdxf imports responsive on macOS.
# Unsigned Cython .so modules can stall for minutes on first load (Gatekeeper).
import os

os.environ.setdefault("EZDXF_DISABLE_C_EXT", "1")
"""


def site_packages() -> Path:
    out = subprocess.check_output(
        [str(VENV_PYTHON), "-c", "import site; print(site.getsitepackages()[0])"],
        text=True,
    ).strip()
    return Path(out)


def write_sitecustomize(target: Path) -> None:
    target.write_text(SITECUSTOMIZE, encoding="utf-8")
    print(f"wrote {target}")


def clear_macos_xattrs(venv_root: Path) -> None:
    if platform.system() != "Darwin":
        return
    native = list(venv_root.rglob("*.so")) + list(venv_root.rglob("*.dylib"))
    if not native:
        return
    print(f"clearing extended attributes on {len(native)} native libraries...")
    for path in native:
        subprocess.run(["xattr", "-c", str(path)], check=False)


def smoke_check() -> None:
    print("import smoke check (build123d, scipy, OCP)...")
    subprocess.check_call(
        [
            str(VENV_PYTHON),
            "-c",
            "import build123d, scipy; from OCP.TopoDS import TopoDS_Shape; print('ok')",
        ],
        cwd=REPO_ROOT,
    )


def main() -> int:
    if not VENV_PYTHON.is_file():
        print(f"missing venv python: {VENV_PYTHON}", file=sys.stderr)
        print("create it first: python3.11 -m venv .venv", file=sys.stderr)
        return 1

    sp = site_packages()
    write_sitecustomize(sp / "sitecustomize.py")
    clear_macos_xattrs(REPO_ROOT / ".venv")
    smoke_check()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
