from .one_d import Edge as Edge, Mixin1D as Mixin1D, Wire as Wire
from .shape_core import Joint as Joint, Shape as Shape, ShapeList as ShapeList, SkipClean as SkipClean, downcast as downcast, shapetype as shapetype, topods_dim as topods_dim
from .three_d import Mixin3D as Mixin3D, Solid as Solid
from .two_d import Face as Face, Shell as Shell
from .utils import tuplify as tuplify, unwrapped_shapetype as unwrapped_shapetype
from .zero_d import Vertex as Vertex
from OCP.TopoDS import TopoDS_Compound, TopoDS_Shape as TopoDS_Shape
from _typeshed import Incomplete
from build123d.build_enums import Align as Align, CenterOf as CenterOf, FontStyle as FontStyle, TextAlign as TextAlign
from build123d.geometry import Axis as Axis, Color as Color, Location as Location, Plane as Plane, TOLERANCE as TOLERANCE, Vector as Vector, VectorLike as VectorLike, logger as logger
from collections.abc import Iterable, Iterator, Sequence
from typing_extensions import Self

class Compound(Mixin3D, Shape[TopoDS_Compound]):
    order: float
    project_to_viewport: Incomplete
    material: Incomplete
    joints: Incomplete
    children: Incomplete
    def __init__(self, obj: TopoDS_Compound | Iterable[Shape] | None = None, label: str = '', color: Color | None = None, material: str = '', joints: dict[str, Joint] | None = None, parent: Compound | None = None, children: Sequence[Shape] | None = None) -> None: ...
    @property
    def volume(self) -> float: ...
    @classmethod
    def cast(cls, obj: TopoDS_Shape) -> Vertex | Edge | Wire | Face | Shell | Solid | Compound: ...
    @classmethod
    def extrude(cls, obj: Shell, direction: VectorLike) -> Compound: ...
    @classmethod
    def make_text(cls, txt: str, font_size: float, font: str = 'Arial', font_path: str | None = None, font_style: FontStyle = ..., text_align: tuple[TextAlign, TextAlign] = ..., align: Align | tuple[Align, Align] | None = None, position_on_path: float = 0.0, text_path: Edge | Wire | None = None) -> Compound: ...
    @classmethod
    def make_triad(cls, axes_scale: float) -> Compound: ...
    def __add__(self, other: None | Shape | Iterable[Shape]) -> Compound | Wire: ...
    def __and__(self, other: Shape | Iterable[Shape]) -> Compound: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[Shape]: ...
    def __len__(self) -> int: ...
    def __sub__(self, other: None | Shape | Iterable[Shape]) -> Compound: ...
    def center(self, center_of: CenterOf = ...) -> Vector: ...
    def compound(self) -> Compound | None: ...
    def compounds(self) -> ShapeList[Compound]: ...
    def do_children_intersect(self, include_parent: bool = False, tolerance: float = 1e-05) -> tuple[bool, tuple[Shape | None, Shape | None], float]: ...
    def get_type(self, obj_type: type[Vertex] | type[Edge] | type[Face] | type[Shell] | type[Solid] | type[Wire]) -> list[Vertex | Edge | Face | Shell | Solid | Wire]: ...
    def unwrap(self, fully: bool = True) -> Self | Shape: ...

class Curve(Compound):
    __add__: Incomplete
    def __matmul__(self, position: float) -> Vector: ...
    def __mod__(self, position: float) -> Vector: ...
    def __xor__(self, position: float) -> Location: ...
    def wires(self) -> ShapeList[Wire]: ...

class Sketch(Compound): ...
class Part(Compound): ...
