from .composite import Compound as Compound, Curve as Curve, Part as Part, Sketch as Sketch
from .shape_core import Shape as Shape, ShapeList as ShapeList, SkipClean as SkipClean, TrimmingTool as TrimmingTool, downcast as downcast, get_top_level_topods_shapes as get_top_level_topods_shapes, shapetype as shapetype, topods_dim as topods_dim, unwrap_topods_compound as unwrap_topods_compound
from .three_d import Solid as Solid
from .two_d import Face as Face, Shell as Shell
from .utils import isclose_b as isclose_b
from .zero_d import Vertex as Vertex, topo_explore_common_vertex as topo_explore_common_vertex
from OCP.BRepAdaptor import BRepAdaptor_CompCurve, BRepAdaptor_Curve
from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeEdge2d as BRepBuilderAPI_MakeEdge2d
from OCP.GccEnt import GccEnt_Position as GccEnt_Position, GccEnt_unqualified as GccEnt_unqualified
from OCP.Geom import Geom_Surface as Geom_Surface
from OCP.Geom2d import Geom2d_CartesianPoint as Geom2d_CartesianPoint, Geom2d_Circle as Geom2d_Circle, Geom2d_Curve as Geom2d_Curve, Geom2d_Point as Geom2d_Point
from OCP.Geom2dAdaptor import Geom2dAdaptor_Curve as Geom2dAdaptor_Curve
from OCP.Geom2dGcc import Geom2dGcc_Circ2d2TanRad as Geom2dGcc_Circ2d2TanRad, Geom2dGcc_QualifiedCurve as Geom2dGcc_QualifiedCurve
from OCP.GeomAPI import GeomAPI as GeomAPI
from OCP.GeomFill import GeomFill_TrihedronLaw as GeomFill_TrihedronLaw
from OCP.TopoDS import TopoDS_Edge, TopoDS_Face, TopoDS_Shape as TopoDS_Shape, TopoDS_Wire
from OCP.gp import gp_Circ2d as gp_Circ2d, gp_Pln as gp_Pln
from build123d.build_enums import AngularDirection as AngularDirection, CenterOf as CenterOf, ContinuityLevel as ContinuityLevel, FrameMethod as FrameMethod, GeomType as GeomType, Keep as Keep, Kind as Kind, PositionMode as PositionMode, Sagitta as Sagitta, Side as Side, Tangency as Tangency
from build123d.geometry import Axis as Axis, Color as Color, DEG2RAD as DEG2RAD, Location as Location, Plane as Plane, TOLERANCE as TOLERANCE, TOL_DIGITS as TOL_DIGITS, Vector as Vector, VectorLike as VectorLike, logger as logger
from collections.abc import Iterable
from typing import Literal, overload
from typing_extensions import Self

class Mixin1D(Shape):
    @property
    def is_closed(self) -> bool: ...
    @property
    def is_forward(self) -> bool: ...
    @property
    def is_interior(self) -> bool: ...
    @property
    def length(self) -> float: ...
    @property
    def radius(self) -> float: ...
    @property
    def volume(self) -> float: ...
    @classmethod
    def cast(cls, obj: TopoDS_Shape) -> Vertex | Edge | Wire: ...
    @classmethod
    def extrude(cls, obj: Shape, direction: VectorLike) -> Edge | Face | Shell | Solid | Compound: ...
    def __add__(self, other: None | Shape | Iterable[Shape]) -> Edge | Wire | ShapeList[Edge]: ...
    def __matmul__(self, position: float) -> Vector: ...
    def __mod__(self, position: float) -> Vector: ...
    def __xor__(self, position: float) -> Location: ...
    def center(self, center_of: CenterOf = ...) -> Vector: ...
    def common_plane(self, *lines: Edge | Wire | None) -> None | Plane: ...
    def curvature_comb(self, count: int = 100, max_tooth_size: float | None = None) -> ShapeList[Edge]: ...
    def derivative_at(self, position: float | VectorLike, order: int = 2, position_mode: PositionMode = ...) -> Vector: ...
    def edge(self) -> Edge | None: ...
    def edges(self) -> ShapeList[Edge]: ...
    def end_point(self) -> Vector: ...
    def intersect(self, *to_intersect: Shape | Vector | Location | Axis | Plane) -> None | ShapeList[Vertex | Edge]: ...
    def location_at(self, distance: float, position_mode: PositionMode = ..., frame_method: FrameMethod = ..., planar: bool | None = None, x_dir: VectorLike | None = None) -> Location: ...
    def locations(self, distances: Iterable[float], position_mode: PositionMode = ..., frame_method: FrameMethod = ..., planar: bool | None = None, x_dir: VectorLike | None = None) -> list[Location]: ...
    def normal(self) -> Vector: ...
    def offset_2d(self, distance: float, kind: Kind = ..., side: Side = ..., closed: bool = True) -> Edge | Wire: ...
    def param_at(self, position: float) -> float: ...
    def perpendicular_line(self, length: float, u_value: float, plane: Plane = ...) -> Edge: ...
    def position_at(self, position: float, position_mode: PositionMode = ...) -> Vector: ...
    def positions(self, distances: Iterable[float], position_mode: PositionMode = ...) -> list[Vector]: ...
    def project(self, face: Face, direction: VectorLike, closest: bool = True) -> Edge | Wire | ShapeList[Edge | Wire]: ...
    def project_to_viewport(self, viewport_origin: VectorLike, viewport_up: VectorLike = (0, 0, 1), look_at: VectorLike | None = None, focus: float | None = None) -> tuple[ShapeList[Edge], ShapeList[Edge]]: ...
    @overload
    def split(self, tool: TrimmingTool, keep: Literal[Keep.TOP, Keep.BOTTOM]) -> Self | list[Self] | None: ...
    @overload
    def split(self, tool: TrimmingTool, keep: Literal[Keep.ALL]) -> list[Self]: ...
    @overload
    def split(self, tool: TrimmingTool, keep: Literal[Keep.BOTH]) -> tuple[Self | list[Self] | None, Self | list[Self] | None]: ...
    @overload
    def split(self, tool: TrimmingTool) -> Self | list[Self] | None: ...
    def start_point(self) -> Vector: ...
    def tangent_angle_at(self, location_param: float = 0.5, position_mode: PositionMode = ..., plane: Plane = ...) -> float: ...
    def tangent_at(self, position: float | VectorLike = 0.5, position_mode: PositionMode = ...) -> Vector: ...
    def vertex(self) -> Vertex | None: ...
    def vertices(self) -> ShapeList[Vertex]: ...
    def wire(self) -> Wire | None: ...
    def wires(self) -> ShapeList[Wire]: ...

class Edge(Mixin1D, Shape[TopoDS_Edge]):
    order: float
    def __init__(self, obj: TopoDS_Edge | Axis | None | None = None, label: str = '', color: Color | None = None, parent: Compound | None = None) -> None: ...
    @property
    def arc_center(self) -> Vector: ...
    @classmethod
    def extrude(cls, obj: Vertex, direction: VectorLike) -> Edge: ...
    @classmethod
    def make_bezier(cls, *cntl_pnts: VectorLike, weights: list[float] | None = None) -> Edge: ...
    @classmethod
    def make_circle(cls, radius: float, plane: Plane = ..., start_angle: float = 360.0, end_angle: float = 360, angular_direction: AngularDirection = ...) -> Edge: ...
    @overload
    @classmethod
    def make_constrained_arcs(cls, tangency_one: tuple[Axis | Edge, Tangency] | Axis | Edge | Vertex | VectorLike, tangency_two: tuple[Axis | Edge, Tangency] | Axis | Edge | Vertex | VectorLike, *, radius: float, sagitta: Sagitta = ...) -> ShapeList[Edge]: ...
    @overload
    @classmethod
    def make_constrained_arcs(cls, tangency_one: tuple[Axis | Edge, Tangency] | Axis | Edge | Vertex | VectorLike, tangency_two: tuple[Axis | Edge, Tangency] | Axis | Edge | Vertex | VectorLike, *, center_on: Axis | Edge, sagitta: Sagitta = ...) -> ShapeList[Edge]: ...
    @overload
    @classmethod
    def make_constrained_arcs(cls, tangency_one: tuple[Axis | Edge, Tangency] | Axis | Edge | Vertex | VectorLike, tangency_two: tuple[Axis | Edge, Tangency] | Axis | Edge | Vertex | VectorLike, tangency_three: tuple[Axis | Edge, Tangency] | Axis | Edge | Vertex | VectorLike, *, sagitta: Sagitta = ...) -> ShapeList[Edge]: ...
    @overload
    @classmethod
    def make_constrained_arcs(cls, tangency_one: tuple[Axis | Edge, Tangency] | Axis | Edge | Vertex | VectorLike, *, center: VectorLike) -> ShapeList[Edge]: ...
    @overload
    @classmethod
    def make_constrained_arcs(cls, tangency_one: tuple[Axis | Edge, Tangency] | Axis | Edge | Vertex | VectorLike, *, radius: float, center_on: Edge) -> ShapeList[Edge]: ...
    @overload
    @classmethod
    def make_constrained_lines(cls, tangency_one: tuple[Edge, Tangency] | Axis | Edge, tangency_two: tuple[Edge, Tangency] | Axis | Edge) -> ShapeList[Edge]: ...
    @overload
    @classmethod
    def make_constrained_lines(cls, tangency_one: tuple[Edge, Tangency] | Edge, tangency_two: Vector) -> ShapeList[Edge]: ...
    @overload
    @classmethod
    def make_constrained_lines(cls, tangency_one: tuple[Edge, Tangency] | Edge, tangency_two: Axis, *, angle: float | None = None, direction: VectorLike | None = None) -> ShapeList[Edge]: ...
    @classmethod
    def make_ellipse(cls, x_radius: float, y_radius: float, plane: Plane = ..., start_angle: float = 360.0, end_angle: float = 360.0, angular_direction: AngularDirection = ...) -> Edge: ...
    @classmethod
    def make_helix(cls, pitch: float, height: float, radius: float, center: VectorLike = (0, 0, 0), normal: VectorLike = (0, 0, 1), angle: float = 0.0, lefthand: bool = False) -> Wire: ...
    @classmethod
    def make_line(cls, point1: VectorLike, point2: VectorLike) -> Edge: ...
    @classmethod
    def make_mid_way(cls, first: Edge, second: Edge, middle: float = 0.5) -> Edge: ...
    @classmethod
    def make_spline(cls, points: list[VectorLike], tangents: list[VectorLike] | None = None, periodic: bool = False, parameters: list[float] | None = None, scale: bool = True, tol: float = 1e-06) -> Edge: ...
    @classmethod
    def make_spline_approx(cls, points: list[VectorLike], tol: float = 0.001, smoothing: tuple[float, float, float] | None = None, min_deg: int = 1, max_deg: int = 6) -> Edge: ...
    @classmethod
    def make_tangent_arc(cls, start: VectorLike, tangent: VectorLike, end: VectorLike) -> Edge: ...
    @classmethod
    def make_three_point_arc(cls, point1: VectorLike, point2: VectorLike, point3: VectorLike) -> Edge: ...
    def close(self) -> Edge | Wire: ...
    def distribute_locations(self, count: int, start: float = 0.0, stop: float = 1.0, positions_only: bool = False) -> list[Location]: ...
    def find_intersection_points(self, other: Axis | Edge | None = None, tolerance: float = ...) -> ShapeList[Vector]: ...
    def find_tangent(self, angle: float) -> list[float]: ...
    def geom_adaptor(self) -> BRepAdaptor_Curve: ...
    def param_at_point(self, point: VectorLike) -> float: ...
    def project_to_shape(self, target_object: Shape, direction: VectorLike | None = None, center: VectorLike | None = None) -> list[Edge]: ...
    def reversed(self, reconstruct: bool = False) -> Edge: ...
    def to_axis(self) -> Axis: ...
    def to_wire(self) -> Wire: ...
    def trim(self, start: float | VectorLike, end: float | VectorLike) -> Edge: ...
    def trim_to_length(self, start: float | VectorLike, length: float) -> Edge: ...

class Wire(Mixin1D, Shape[TopoDS_Wire]):
    order: float
    @overload
    def __init__(self, obj: TopoDS_Wire, label: str = '', color: Color | None = None, parent: Compound | None = None) -> None: ...
    @overload
    def __init__(self, edge: Edge, label: str = '', color: Color | None = None, parent: Compound | None = None) -> None: ...
    @overload
    def __init__(self, wire: Wire, label: str = '', color: Color | None = None, parent: Compound | None = None) -> None: ...
    @overload
    def __init__(self, wire: Curve, label: str = '', color: Color | None = None, parent: Compound | None = None) -> None: ...
    @overload
    def __init__(self, edges: Iterable[Edge], sequenced: bool = False, label: str = '', color: Color | None = None, parent: Compound | None = None) -> None: ...
    @classmethod
    def combine(cls, wires: Iterable[Wire | Edge], tol: float = 1e-09) -> ShapeList[Wire]: ...
    @classmethod
    def extrude(cls, obj: Shape, direction: VectorLike) -> Wire: ...
    @classmethod
    def make_circle(cls, radius: float, plane: Plane = ...) -> Wire: ...
    @classmethod
    def make_convex_hull(cls, edges: Iterable[Edge], tolerance: float = 0.001) -> Wire: ...
    @classmethod
    def make_ellipse(cls, x_radius: float, y_radius: float, plane: Plane = ..., start_angle: float = 360.0, end_angle: float = 360.0, angular_direction: AngularDirection = ..., closed: bool = True) -> Wire: ...
    @classmethod
    def make_polygon(cls, vertices: Iterable[VectorLike], close: bool = True) -> Wire: ...
    @classmethod
    def make_rect(cls, width: float, height: float, plane: Plane = ...) -> Wire: ...
    @staticmethod
    def order_chamfer_edges(reference_edge: Edge | None, edges: tuple[Edge, Edge]) -> tuple[Edge, Edge]: ...
    def chamfer_2d(self, distance: float, distance2: float, vertices: Iterable[Vertex], edge: Edge | None = None) -> Wire: ...
    def close(self) -> Wire: ...
    def fillet_2d(self, radius: float, vertices: Iterable[Vertex]) -> Wire: ...
    def fix_degenerate_edges(self, precision: float) -> Wire: ...
    def geom_adaptor(self) -> BRepAdaptor_CompCurve: ...
    def order_edges(self) -> ShapeList[Edge]: ...
    def param_at_point(self, point: VectorLike) -> float: ...
    def project_to_shape(self, target_object: Shape, direction: VectorLike | None = None, center: VectorLike | None = None) -> list[Wire]: ...
    def stitch(self, other: Wire) -> Wire: ...
    def to_wire(self) -> Wire: ...
    def trim(self, start: float | VectorLike, end: float | VectorLike) -> Wire: ...

def edges_to_wires(edges: Iterable[Edge], tol: float = 1e-06) -> ShapeList[Wire]: ...
def offset_topods_face(face: TopoDS_Face, amount: float) -> TopoDS_Shape: ...
def topo_explore_connected_edges(edge: Edge, parent: Shape | None = None, continuity: ContinuityLevel = ...) -> ShapeList[Edge]: ...
def topo_explore_connected_faces(edge: Edge, parent: Shape | None = None) -> list[TopoDS_Face]: ...
