import OCP.GeomAbs as ga
import abc
import types
from .composite import Compound as Compound
from .one_d import Edge as Edge, Wire as Wire
from .three_d import Solid as Solid
from .two_d import Face as Face, Shell as Shell
from .zero_d import Vertex as Vertex
from IPython.lib.pretty import RepresentationPrinter as RepresentationPrinter
from OCP.BRepAlgoAPI import BRepAlgoAPI_BooleanOperation as BRepAlgoAPI_BooleanOperation, BRepAlgoAPI_Splitter as BRepAlgoAPI_Splitter
from OCP.TopAbs import TopAbs_ShapeEnum
from OCP.TopoDS import TopoDS_Compound, TopoDS_Shape
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from anytree import NodeMixin
from build123d.build_enums import CenterOf as CenterOf, GeomType as GeomType, Keep as Keep, SortBy as SortBy, Transition as Transition
from build123d.build_part import BuildPart as BuildPart
from build123d.geometry import Axis as Axis, BoundBox as BoundBox, Color as Color, ColorLike as ColorLike, DEG2RAD as DEG2RAD, Location as Location, Matrix as Matrix, OrientedBoundBox as OrientedBoundBox, Plane as Plane, TOLERANCE as TOLERANCE, Vector as Vector, VectorLike as VectorLike, logger as logger
from collections.abc import Callable as Callable, Iterable, Iterator
from typing import Any, Generic, Literal, Protocol, SupportsIndex, TypeVar, overload
from typing_extensions import Self

Shapes: Incomplete
TrimmingTool: Incomplete
TOPODS = TypeVar('TOPODS', bound=TopoDS_Shape)

class Shape(NodeMixin, Generic[TOPODS], metaclass=abc.ABCMeta):
    shape_LUT: Incomplete
    shape_properties_LUT: Incomplete
    inverse_shape_LUT: Incomplete
    downcast_LUT: Incomplete
    geom_LUT_EDGE: dict[ga.GeomAbs_CurveType, GeomType]
    geom_LUT_FACE: dict[ga.GeomAbs_SurfaceType, GeomType]
    class _DisplayNode(NodeMixin):
        label: Incomplete
        address: Incomplete
        position: Incomplete
        parent: Incomplete
        children: list[Shape]
        def __init__(self, label: str = '', address: int | None = None, position: Vector | Location | None = None, parent: Shape._DisplayNode | None = None) -> None: ...
    wrapped: TOPODS | None
    for_construction: bool
    label: Incomplete
    color: Incomplete
    parent: Incomplete
    topo_parent: Shape | None
    def __init__(self, obj: TopoDS_Shape | None = None, label: str = '', color: ColorLike | None = None, parent: Compound | None = None) -> None: ...
    @property
    def area(self) -> float: ...
    @property
    def color(self) -> None | Color: ...
    @color.setter
    def color(self, value: ColorLike | None) -> None: ...
    @property
    def geom_type(self) -> GeomType: ...
    @property
    def is_manifold(self) -> bool: ...
    @property
    def is_null(self) -> bool: ...
    @property
    def is_planar_face(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def global_location(self) -> Location: ...
    @property
    def location(self) -> Location: ...
    @location.setter
    def location(self, value: Location): ...
    @property
    def matrix_of_inertia(self) -> list[list[float]]: ...
    @property
    def orientation(self) -> Vector: ...
    location: Incomplete
    @orientation.setter
    def orientation(self, rotations: VectorLike): ...
    @property
    def position(self) -> Vector: ...
    @position.setter
    def position(self, value: VectorLike): ...
    @property
    def principal_properties(self) -> list[tuple[Vector, float]]: ...
    @property
    def shape_type(self) -> Shapes: ...
    @property
    def static_moments(self) -> tuple[float, float, float]: ...
    @classmethod
    @abstractmethod
    def cast(cls, obj: TopoDS_Shape) -> Self: ...
    @classmethod
    @abstractmethod
    def extrude(cls, obj: Shape, direction: VectorLike) -> Edge | Face | Shell | Solid | Compound: ...
    @staticmethod
    def combined_center(objects: Iterable[Shape], center_of: CenterOf = ...) -> Vector: ...
    @staticmethod
    def compute_mass(obj: Shape) -> float: ...
    @staticmethod
    def get_shape_list(shape: Shape, entity_type: Literal['Vertex', 'Edge', 'Wire', 'Face', 'Shell', 'Solid', 'Compound']) -> ShapeList: ...
    @staticmethod
    def get_single_shape(shape: Shape, entity_type: Literal['Vertex', 'Edge', 'Wire', 'Face', 'Shell', 'Solid', 'Compound']) -> Shape | None: ...
    def __add__(self, other: None | Shape | Iterable[Shape]) -> Self | ShapeList[Self]: ...
    def __and__(self, other: Shape | Iterable[Shape]) -> None | Self | ShapeList[Self]: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo) -> Self: ...
    def __eq__(self, other) -> bool: ...
    def __hash__(self) -> int: ...
    def __rmul__(self, other): ...
    def __sub__(self, other: None | Shape | Iterable[Shape]) -> Self | ShapeList[Self]: ...
    def bounding_box(self, tolerance: float | None = None, optimal: bool = True) -> BoundBox: ...
    def clean(self) -> Self: ...
    def closest_points(self, other: Shape | VectorLike) -> tuple[Vector, Vector]: ...
    def compound(self) -> Compound | None: ...
    def compounds(self) -> ShapeList[Compound]: ...
    def copy_attributes_to(self, target: Shape, exceptions: Iterable[str] | None = None): ...
    def cut(self, *to_cut: Shape) -> Self | ShapeList[Self]: ...
    def distance(self, other: Shape) -> float: ...
    def distance_to(self, other: Shape | VectorLike) -> float: ...
    def distance_to_with_closest_points(self, other: Shape | VectorLike) -> tuple[float, Vector, Vector]: ...
    def distances(self, *others: Shape) -> Iterator[float]: ...
    def edge(self) -> Edge | None: ...
    def edges(self) -> ShapeList[Edge]: ...
    def entities(self, topo_type: Shapes) -> list[TopoDS_Shape]: ...
    def face(self) -> Face | None: ...
    def faces(self) -> ShapeList[Face]: ...
    def faces_intersected_by_axis(self, axis: Axis, tol: float = 0.0001) -> ShapeList[Face]: ...
    def fix(self) -> Self: ...
    def fuse(self, *to_fuse: Shape, glue: bool = False, tol: float | None = None) -> Self | ShapeList[Self]: ...
    def get_top_level_shapes(self) -> ShapeList[Shape]: ...
    def intersect(self, *to_intersect: Shape | Vector | Location | Axis | Plane) -> None | Self | ShapeList[Self]: ...
    def is_equal(self, other: Shape) -> bool: ...
    def is_same(self, other: Shape) -> bool: ...
    def locate(self, loc: Location) -> Self: ...
    def located(self, loc: Location) -> Self: ...
    def mesh(self, tolerance: float, angular_tolerance: float = 0.1): ...
    def mirror(self, mirror_plane: Plane | None = None) -> Self: ...
    def move(self, loc: Location) -> Self: ...
    def moved(self, loc: Location) -> Self: ...
    def oriented_bounding_box(self) -> OrientedBoundBox: ...
    def project_faces(self, faces: list[Face] | Compound, path: Wire | Edge, start: float = 0) -> ShapeList[Face]: ...
    def radius_of_gyration(self, axis: Axis) -> float: ...
    def relocate(self, loc: Location): ...
    def rotate(self, axis: Axis, angle: float) -> Self: ...
    def scale(self, factor: float) -> Self: ...
    def shell(self) -> Shell | None: ...
    def shells(self) -> ShapeList[Shell]: ...
    def show_topology(self, limit_class: Literal['Compound', 'Edge', 'Face', 'Shell', 'Solid', 'Vertex', 'Wire'] = 'Vertex', show_center: bool | None = None) -> str: ...
    def solid(self) -> Solid | None: ...
    def solids(self) -> ShapeList[Solid]: ...
    @overload
    def split_by_perimeter(self, perimeter: Edge | Wire, keep: Literal[Keep.INSIDE, Keep.OUTSIDE]) -> Face | Shell | ShapeList[Face] | None: ...
    @overload
    def split_by_perimeter(self, perimeter: Edge | Wire, keep: Literal[Keep.BOTH]) -> tuple[Face | Shell | ShapeList[Face] | None, Face | Shell | ShapeList[Face] | None]: ...
    @overload
    def split_by_perimeter(self, perimeter: Edge | Wire) -> Face | Shell | ShapeList[Face] | None: ...
    def tessellate(self, tolerance: float, angular_tolerance: float = 0.1) -> tuple[list[Vector], list[tuple[int, int, int]]]: ...
    def to_splines(self, degree: int = 3, tolerance: float = 0.001, nurbs: bool = False) -> Self: ...
    def transform_geometry(self, t_matrix: Matrix) -> Self: ...
    def transform_shape(self, t_matrix: Matrix) -> Self: ...
    def transformed(self, rotate: VectorLike = (0, 0, 0), offset: VectorLike = (0, 0, 0)) -> Self: ...
    def translate(self, vector: VectorLike) -> Self: ...
    def wire(self) -> Wire | None: ...
    def wires(self) -> ShapeList[Wire]: ...

class Comparable(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def __eq__(self, other: Any) -> bool: ...
    @abstractmethod
    def __lt__(self, other: Any) -> bool: ...

class SupportsLessThan(Protocol):
    def __lt__(self, other: Any) -> bool: ...
T = TypeVar('T', bound=Shape | Vector)
K = TypeVar('K', bound=SupportsLessThan)

class ShapePredicate(Protocol):
    def __call__(self, shape: Shape) -> bool: ...

class GroupBy(Generic[T, K]):
    key_to_group_index: list[tuple[K, int]]
    groups: list[ShapeList[T]]
    key_f: Incomplete
    def __init__(self, key_f: Callable[[T], K], shapelist: Iterable[T], *, reverse: bool = False) -> None: ...
    def __getitem__(self, key: int): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def group(self, key: K): ...
    def group_for(self, shape: T): ...

class ShapeList(list[T]):
    @property
    def first(self) -> T: ...
    @property
    def last(self) -> T: ...
    def __add__(self, other: Shape | Iterable[Shape]) -> ShapeList[T]: ...
    def __iadd__(self, other: Shape | Iterable[Shape]) -> Self: ...
    def __and__(self, other: ShapeList) -> ShapeList[T]: ...
    def __eq__(self, other: object) -> bool: ...
    @overload
    def __getitem__(self, key: SupportsIndex) -> T: ...
    @overload
    def __getitem__(self, key: slice) -> ShapeList[T]: ...
    def __gt__(self, sort_by: Axis | SortBy = ...) -> ShapeList[T]: ...
    def __lshift__(self, group_by: Axis | SortBy = ...) -> ShapeList[T]: ...
    def __lt__(self, sort_by: Axis | SortBy = ...) -> ShapeList[T]: ...
    def __ne__(self, other: ShapeList) -> bool: ...
    def __or__(self, filter_by: Axis | GeomType = ...) -> ShapeList[T]: ...
    def __rshift__(self, group_by: Axis | SortBy = ...) -> ShapeList[T]: ...
    def __sub__(self, other: ShapeList) -> ShapeList[T]: ...
    def center(self) -> Vector: ...
    def compound(self) -> Compound: ...
    def compounds(self) -> ShapeList[Compound]: ...
    def edge(self) -> Edge: ...
    def edges(self) -> ShapeList[Edge]: ...
    def face(self) -> Face: ...
    def faces(self) -> ShapeList[Face]: ...
    def filter_by(self, filter_by: ShapePredicate | Axis | Plane | GeomType | property, reverse: bool = False, tolerance: float = 1e-05) -> ShapeList[T]: ...
    def filter_by_position(self, axis: Axis, minimum: float, maximum: float, inclusive: tuple[bool, bool] = (True, True)) -> ShapeList[T]: ...
    def group_by(self, group_by: Callable[[Shape], K] | Axis | Edge | Wire | SortBy | property = ..., reverse: bool = False, tol_digits: int = 6) -> GroupBy[T, K]: ...
    def shell(self) -> Shell: ...
    def shells(self) -> ShapeList[Shell]: ...
    def solid(self) -> Solid: ...
    def solids(self) -> ShapeList[Solid]: ...
    def sort_by(self, sort_by: Axis | Callable[[T], K] | Edge | Wire | SortBy | property = ..., reverse: bool = False) -> ShapeList[T]: ...
    def sort_by_distance(self, other: Shape | VectorLike, reverse: bool = False) -> ShapeList[T]: ...
    def vertex(self) -> Vertex: ...
    def vertices(self) -> ShapeList[Vertex]: ...
    def wire(self) -> Wire: ...
    def wires(self) -> ShapeList[Wire]: ...

class Joint(ABC, metaclass=abc.ABCMeta):
    label: Incomplete
    parent: Incomplete
    connected_to: Joint | None
    def __init__(self, label: str, parent: BuildPart | Solid | Compound) -> None: ...
    @property
    @abstractmethod
    def location(self) -> Location: ...
    @property
    @abstractmethod
    def symbol(self) -> Compound: ...
    @abstractmethod
    def connect_to(self, *args, **kwargs): ...
    @abstractmethod
    def relative_to(self, *args, **kwargs) -> Location: ...

class SkipClean:
    clean: bool
    def __enter__(self) -> None: ...
    def __exit__(self, exception_type: type[BaseException] | None, exception_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

def downcast(obj: TopoDS_Shape) -> TopoDS_Shape: ...
def fix(obj: TopoDS_Shape) -> TopoDS_Shape: ...
def get_top_level_topods_shapes(topods_shape: TopoDS_Shape | None) -> list[TopoDS_Shape]: ...
def shapetype(obj: TopoDS_Shape | None) -> TopAbs_ShapeEnum: ...
def topods_dim(topods: TopoDS_Shape) -> int | None: ...
def unwrap_topods_compound(compound: TopoDS_Compound, fully: bool = True) -> TopoDS_Compound | TopoDS_Shape: ...
