from .composite import Compound as Compound, Curve as Curve, Part as Part, Sketch as Sketch
from .one_d import Edge as Edge, Mixin1D as Mixin1D, Wire as Wire
from .shape_core import Joint as Joint, Shape as Shape, ShapeList as ShapeList, downcast as downcast, shapetype as shapetype
from .two_d import Face as Face, Mixin2D as Mixin2D, Shell as Shell, sort_wires_by_build_order as sort_wires_by_build_order
from .utils import find_max_dimension as find_max_dimension
from .zero_d import Vertex as Vertex
from OCP.TopoDS import TopoDS_Shape as TopoDS_Shape, TopoDS_Solid, TopoDS_Wire as TopoDS_Wire
from _typeshed import Incomplete
from build123d.build_enums import CenterOf as CenterOf, GeomType as GeomType, Kind as Kind, Transition as Transition, Until as Until
from build123d.geometry import Axis as Axis, BoundBox as BoundBox, Color as Color, DEG2RAD as DEG2RAD, Location as Location, OrientedBoundBox as OrientedBoundBox, Plane as Plane, Vector as Vector, VectorLike as VectorLike
from collections.abc import Iterable
from typing_extensions import Self

class Mixin3D(Shape):
    project_to_viewport: Incomplete
    split: Incomplete
    find_intersection_points: Incomplete
    vertices: Incomplete
    vertex: Incomplete
    edges: Incomplete
    edge: Incomplete
    wires: Incomplete
    wire: Incomplete
    faces: Incomplete
    face: Incomplete
    shells: Incomplete
    shell: Incomplete
    @classmethod
    def cast(cls, obj: TopoDS_Shape) -> Self: ...
    @classmethod
    def extrude(cls, obj: Shape, direction: VectorLike) -> Edge | Face | Shell | Solid | Compound: ...
    def center(self, center_of: CenterOf = ...) -> Vector: ...
    def chamfer(self, length: float, length2: float | None, edge_list: Iterable[Edge], face: Face | None = None) -> Self: ...
    def dprism(self, basis: Face | None, bounds: list[Face | Wire], depth: float | None = None, taper: float = 0, up_to_face: Face | None = None, thru_all: bool = True, additive: bool = True) -> Solid: ...
    def fillet(self, radius: float, edge_list: Iterable[Edge]) -> Self: ...
    def hollow(self, faces: Iterable[Face] | None, thickness: float, tolerance: float = 0.0001, kind: Kind = ...) -> Solid: ...
    def is_inside(self, point: VectorLike, tolerance: float = 1e-06) -> bool: ...
    def max_fillet(self, edge_list: Iterable[Edge], tolerance: float = 0.1, max_iterations: int = 10) -> float: ...
    def offset_3d(self, openings: Iterable[Face] | None, thickness: float, tolerance: float = 0.0001, kind: Kind = ...) -> Solid: ...
    def solid(self) -> Solid | None: ...
    def solids(self) -> ShapeList[Solid]: ...

class Solid(Mixin3D, Shape[TopoDS_Solid]):
    order: float
    material: Incomplete
    joints: Incomplete
    def __init__(self, obj: TopoDS_Solid | Shell | None = None, label: str = '', color: Color | None = None, material: str = '', joints: dict[str, Joint] | None = None, parent: Compound | None = None) -> None: ...
    @property
    def volume(self) -> float: ...
    @classmethod
    def extrude(cls, obj: Face, direction: VectorLike) -> Solid: ...
    @classmethod
    def extrude_linear_with_rotation(cls, section: Face | Wire, center: VectorLike, normal: VectorLike, angle: float, inner_wires: list[Wire] | None = None) -> Solid: ...
    @classmethod
    def extrude_taper(cls, profile: Face, direction: VectorLike, taper: float, flip_inner: bool = True) -> Solid: ...
    @classmethod
    def extrude_until(cls, section: Face, target_object: Compound | Solid, direction: VectorLike, until: Until = ...) -> Compound | Solid: ...
    @classmethod
    def from_bounding_box(cls, bbox: BoundBox | OrientedBoundBox) -> Solid: ...
    @classmethod
    def make_box(cls, length: float, width: float, height: float, plane: Plane = ...) -> Solid: ...
    @classmethod
    def make_cone(cls, base_radius: float, top_radius: float, height: float, plane: Plane = ..., angle: float = 360) -> Solid: ...
    @classmethod
    def make_cylinder(cls, radius: float, height: float, plane: Plane = ..., angle: float = 360) -> Solid: ...
    @classmethod
    def make_loft(cls, objs: Iterable[Vertex | Wire], ruled: bool = False) -> Solid: ...
    @classmethod
    def make_sphere(cls, radius: float, plane: Plane = ..., angle1: float = -90, angle2: float = 90, angle3: float = 360) -> Solid: ...
    @classmethod
    def make_torus(cls, major_radius: float, minor_radius: float, plane: Plane = ..., start_angle: float = 0, end_angle: float = 360, major_angle: float = 360) -> Solid: ...
    @classmethod
    def make_wedge(cls, delta_x: float, delta_y: float, delta_z: float, min_x: float, min_z: float, max_x: float, max_z: float, plane: Plane = ...) -> Solid: ...
    @classmethod
    def revolve(cls, section: Face | Wire, angle: float, axis: Axis, inner_wires: list[Wire] | None = None) -> Solid: ...
    @classmethod
    def sweep(cls, section: Face | Wire, path: Wire | Edge, inner_wires: list[Wire] | None = None, make_solid: bool = True, is_frenet: bool = False, mode: Vector | Wire | Edge | None = None, transition: Transition = ...) -> Solid: ...
    @classmethod
    def sweep_multi(cls, profiles: Iterable[Wire | Face], path: Wire | Edge, make_solid: bool = True, is_frenet: bool = False, binormal: Vector | Wire | Edge | None = None) -> Solid: ...
    @classmethod
    def thicken(cls, surface: Face | Shell, depth: float, normal_override: VectorLike | None = None) -> Solid: ...
    def draft(self, faces: Iterable[Face], neutral_plane: Plane, angle: float) -> Solid: ...

class DraftAngleError(RuntimeError):
    face: Incomplete
    problematic_shape: Incomplete
    def __init__(self, message, face=None, problematic_shape=None) -> None: ...
