import abc
from .composite import Compound as Compound, Curve as Curve
from .one_d import Edge as Edge, Mixin1D as Mixin1D, Wire as Wire
from .shape_core import Shape as Shape, ShapeList as ShapeList, SkipClean as SkipClean, downcast as downcast, get_top_level_topods_shapes as get_top_level_topods_shapes, shapetype as shapetype
from .three_d import Solid as Solid
from .utils import find_max_dimension as find_max_dimension
from .zero_d import Vertex as Vertex
from OCP.BRepAdaptor import BRepAdaptor_Surface as BRepAdaptor_Surface
from OCP.Geom import Geom_Surface as Geom_Surface
from OCP.TopoDS import TopoDS_Face, TopoDS_Shape, TopoDS_Shell
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from build123d.build_enums import CenterOf as CenterOf, ContinuityLevel as ContinuityLevel, GeomType as GeomType, Keep as Keep, SortBy as SortBy, Transition as Transition
from build123d.geometry import Axis as Axis, Color as Color, DEG2RAD as DEG2RAD, Location as Location, OrientedBoundBox as OrientedBoundBox, Plane as Plane, TOLERANCE as TOLERANCE, Vector as Vector, VectorLike as VectorLike
from collections.abc import Iterable
from typing import Any, TypeVar, overload
from typing_extensions import Self

T = TypeVar('T', Edge, Wire, 'Face')

class Mixin2D(ABC, Shape, metaclass=abc.ABCMeta):
    project_to_viewport: Incomplete
    split: Incomplete
    vertices: Incomplete
    vertex: Incomplete
    edges: Incomplete
    edge: Incomplete
    wires: Incomplete
    @classmethod
    def cast(cls, obj: TopoDS_Shape) -> Vertex | Edge | Wire | Face | Shell: ...
    @classmethod
    def extrude(cls, obj: Shape, direction: VectorLike) -> Edge | Face | Shell | Solid | Compound: ...
    def __neg__(self) -> Self: ...
    def face(self) -> Face | None: ...
    def faces(self) -> ShapeList[Face]: ...
    def find_intersection_points(self, other: Axis, tolerance: float = ...) -> list[tuple[Vector, Vector]]: ...
    @abstractmethod
    def location_at(self, *args: Any, **kwargs: Any) -> Location: ...
    def offset(self, amount: float) -> Self: ...
    def shell(self) -> Shell | None: ...
    def shells(self) -> ShapeList[Shell]: ...

class Face(Mixin2D, Shape[TopoDS_Face]):
    order: float
    @overload
    def __init__(self, obj: TopoDS_Face, label: str = '', color: Color | None = None, parent: Compound | None = None) -> None: ...
    @overload
    def __init__(self, outer_wire: Wire, inner_wires: Iterable[Wire] | None = None, label: str = '', color: Color | None = None, parent: Compound | None = None) -> None: ...
    @property
    def area_without_holes(self) -> float: ...
    @property
    def axis_of_rotation(self) -> None | Axis: ...
    @property
    def axes_of_symmetry(self) -> list[Axis]: ...
    @property
    def center_location(self) -> Location: ...
    @property
    def geometry(self) -> None | str: ...
    @property
    def is_circular_convex(self) -> bool: ...
    @property
    def is_circular_concave(self) -> bool: ...
    @property
    def is_planar(self) -> bool: ...
    @property
    def length(self) -> None | float: ...
    @property
    def radii(self) -> None | tuple[float, float]: ...
    @property
    def radius(self) -> None | float: ...
    @property
    def volume(self) -> float: ...
    @property
    def width(self) -> None | float: ...
    @classmethod
    def extrude(cls, obj: Edge, direction: VectorLike) -> Face: ...
    @classmethod
    def make_bezier_surface(cls, points: list[list[VectorLike]], weights: list[list[float]] | None = None) -> Face: ...
    @classmethod
    def make_gordon_surface(cls, profiles: Iterable[VectorLike | Edge], guides: Iterable[VectorLike | Edge], tolerance: float = 0.0003) -> Face: ...
    @classmethod
    def make_plane(cls, plane: Plane = ...) -> Face: ...
    @classmethod
    def make_rect(cls, width: float, height: float, plane: Plane = ...) -> Face: ...
    @classmethod
    def make_surface(cls, exterior: Wire | Iterable[Edge], surface_points: Iterable[VectorLike] | None = None, interior_wires: Iterable[Wire] | None = None) -> Face: ...
    @classmethod
    def make_surface_from_array_of_points(cls, points: list[list[VectorLike]], tol: float = 0.01, smoothing: tuple[float, float, float] | None = None, min_deg: int = 1, max_deg: int = 3) -> Face: ...
    @overload
    @classmethod
    def make_surface_from_curves(cls, edge1: Edge, edge2: Edge) -> Face: ...
    @overload
    @classmethod
    def make_surface_from_curves(cls, wire1: Wire, wire2: Wire) -> Face: ...
    @classmethod
    def make_surface_patch(cls, edge_face_constraints: Iterable[tuple[Edge, Face, ContinuityLevel]] | None = None, edge_constraints: Iterable[Edge] | None = None, point_constraints: Iterable[VectorLike] | None = None) -> Face: ...
    @classmethod
    def revolve(cls, profile: Edge, angle: float, axis: Axis) -> Face: ...
    @classmethod
    def sew_faces(cls, faces: Iterable[Face]) -> list[ShapeList[Face]]: ...
    @classmethod
    def sweep(cls, profile: Curve | Edge | Wire, path: Curve | Edge | Wire, transition=...) -> Face: ...
    def center(self, center_of: CenterOf = ...) -> Vector: ...
    def chamfer_2d(self, distance: float, distance2: float, vertices: Iterable[Vertex], edge: Edge | None = None) -> Face: ...
    def fillet_2d(self, radius: float, vertices: Iterable[Vertex]) -> Face: ...
    def geom_adaptor(self) -> Geom_Surface: ...
    def inner_wires(self) -> ShapeList[Wire]: ...
    def is_coplanar(self, plane: Plane) -> bool: ...
    def is_inside(self, point: VectorLike, tolerance: float = 1e-06) -> bool: ...
    @overload
    def location_at(self, surface_point: VectorLike | None = None, *, x_dir: VectorLike | None = None) -> Location: ...
    @overload
    def location_at(self, u: float, v: float, *, x_dir: VectorLike | None = None) -> Location: ...
    def make_holes(self, interior_wires: list[Wire]) -> Face: ...
    @overload
    def normal_at(self, surface_point: VectorLike | None = None) -> Vector: ...
    @overload
    def normal_at(self, u: float, v: float) -> Vector: ...
    def outer_wire(self) -> Wire: ...
    def position_at(self, u: float, v: float) -> Vector: ...
    def project_to_shape(self, target_object: Shape, direction: VectorLike) -> ShapeList[Face | Shell]: ...
    def to_arcs(self, tolerance: float = 0.001) -> Face: ...
    def without_holes(self) -> Face: ...
    def wire(self) -> Wire: ...
    @overload
    def wrap(self, planar_shape: Edge, surface_loc: Location, tolerance: float = 0.001, extension_factor: float = 0.1) -> Edge: ...
    @overload
    def wrap(self, planar_shape: Wire, surface_loc: Location, tolerance: float = 0.001, extension_factor: float = 0.1) -> Wire: ...
    @overload
    def wrap(self, planar_shape: Face, surface_loc: Location, tolerance: float = 0.001, extension_factor: float = 0.1) -> Face: ...
    def wrap_faces(self, faces: Iterable[Face], path: Wire | Edge, start: float = 0.0) -> ShapeList[Face]: ...

class Shell(Mixin2D, Shape[TopoDS_Shell]):
    order: float
    def __init__(self, obj: TopoDS_Shell | Face | Iterable[Face] | None = None, label: str = '', color: Color | None = None, parent: Compound | None = None) -> None: ...
    @property
    def volume(self) -> float: ...
    @classmethod
    def extrude(cls, obj: Wire, direction: VectorLike) -> Shell: ...
    @classmethod
    def make_loft(cls, objs: Iterable[Vertex | Wire], ruled: bool = False) -> Shell: ...
    @classmethod
    def revolve(cls, profile: Curve | Wire, angle: float, axis: Axis) -> Face: ...
    @classmethod
    def sweep(cls, profile: Curve | Edge | Wire, path: Curve | Edge | Wire, transition=...) -> Shell: ...
    def center(self) -> Vector: ...
    def location_at(self, surface_point: VectorLike, *, x_dir: VectorLike | None = None) -> Location: ...

def sort_wires_by_build_order(wire_list: list[Wire]) -> list[list[Wire]]: ...
