from .one_d import Edge as Edge, Wire as Wire
from .shape_core import Shape as Shape, ShapeList as ShapeList, downcast as downcast, shapetype as shapetype, unwrap_topods_compound as unwrap_topods_compound
from .zero_d import Vertex as Vertex
from OCP.BRepAlgoAPI import BRepAlgoAPI_BooleanOperation as BRepAlgoAPI_BooleanOperation, BRepAlgoAPI_Splitter as BRepAlgoAPI_Splitter
from OCP.TopAbs import TopAbs_ShapeEnum
from OCP.TopoDS import TopoDS_Shape as TopoDS_Shape
from build123d.geometry import BoundBox as BoundBox, TOLERANCE as TOLERANCE, Vector as Vector, VectorLike as VectorLike
from collections.abc import Iterable
from typing import Any

def delta(shapes_one: Iterable[Shape], shapes_two: Iterable[Shape]) -> list[Shape]: ...
def find_max_dimension(shapes: Shape | Iterable[Shape]) -> float: ...
def isclose_b(x: float, y: float, rel_tol: float = 1e-09, abs_tol: float = 1e-14) -> bool: ...
def new_edges(*objects: Shape, combined: Shape) -> ShapeList[Edge]: ...
def polar(length: float, angle: float) -> tuple[float, float]: ...
def tuplify(obj: Any, dim: int) -> tuple | None: ...
def unwrapped_shapetype(obj: Shape) -> TopAbs_ShapeEnum: ...
