from .one_d import Edge as Edge, Wire as Wire
from .shape_core import Shape as Shape, ShapeList as ShapeList, downcast as downcast, shapetype as shapetype
from OCP.TopoDS import TopoDS_Edge, TopoDS_Shape as TopoDS_Shape, TopoDS_Vertex
from build123d.geometry import Axis as Axis, Location as Location, Matrix as Matrix, Plane as Plane, Vector as Vector, VectorLike as VectorLike
from collections.abc import Iterable
from typing import overload
from typing_extensions import Self

class Vertex(Shape[TopoDS_Vertex]):
    order: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ocp_vx: TopoDS_Vertex) -> None: ...
    @overload
    def __init__(self, X: float, Y: float, Z: float) -> None: ...
    @overload
    def __init__(self, v: Iterable[float]) -> None: ...
    @property
    def volume(self) -> float: ...
    @classmethod
    def cast(cls, obj: TopoDS_Shape) -> Self: ...
    @classmethod
    def extrude(cls, obj: Shape, direction: VectorLike) -> Vertex: ...
    def intersect(self, *to_intersect: Shape | Vector | Location | Axis | Plane) -> ShapeList[Vertex] | None: ...
    def __add__(self, other: Vertex | Vector | tuple[float, float, float]) -> Vertex: ...
    def __and__(self, *args, **kwargs) -> None: ...
    vertex_index: int
    def __iter__(self): ...
    def __next__(self): ...
    def __sub__(self, other: Vertex | Vector | tuple) -> Vertex: ...
    def center(self) -> Vector: ...
    def to_tuple(self) -> tuple[float, float, float]: ...
    def transform_shape(self, t_matrix: Matrix) -> Vertex: ...
    def vertex(self) -> Vertex: ...
    def vertices(self) -> ShapeList[Vertex]: ...

def topo_explore_common_vertex(edge1: Edge | TopoDS_Edge, edge2: Edge | TopoDS_Edge) -> Vertex | None: ...
